#!/usr/bin/env bash
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝

########### Def vars ###########

# Retrieve the $rice_path variables
source "${HOME}"/.config/punk_records/Poneglyph

# Set environment variables
export PATH="$rice_path/src:$PATH"
export XDG_CURRENT_DESKTOP='bspwm'

## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

#  ╦ ╦╔═╗╦═╗╦╔═╔═╗╔═╗╔═╗╔═╗╔═╗╔═╗
#  ║║║║ ║╠╦╝╠╩╗╚═╗╠═╝╠═╣║  ║╣ ╚═╗
#  ╚╩╝╚═╝╩╚═╩ ╩╚═╝╩  ╩ ╩╚═╝╚═╝╚═╝

# Get the name of the primary monitor
INTERNAL_MONITOR=$(xrandr | grep "connected primary" | awk '{print $1}')
# Get the list of connected monitors excluding the primary monitor
EXTERNAL_MONITOR=$(xrandr | grep "connected" | grep -v "primary" | awk '{print $1}')

if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
	bspc monitor "$INTERNAL_MONITOR" -d '1' '2' '3' '4' '5' '6' '7' '8' 
	bspc monitor "$EXTERNAL_MONITOR" -d '1' '2' '3' '4' '5' '6' '7' '8' 
	bspc wm -O  "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
else
	bspc monitor "$INTERNAL_MONITOR" -d '1' '2' '3' '4' '5' '6' '7' '8'
fi

#  ╔╗ ╔═╗╔═╗╦ ╦╔╦╗  ╔═╗╔═╗╔╗╔╔═╗╦╔═╗
#  ╠╩╗╚═╗╠═╝║║║║║║  ║  ║ ║║║║╠╣ ║║ ╦
#  ╚═╝╚═╝╩  ╚╩╝╩ ╩  ╚═╝╚═╝╝╚╝╚  ╩╚═╝

bspc config external_rules_command $external_rules_cfgfile

bspc config split_ratio                   0.5
bspc config single_monocle                true
bspc config borderless_monocle            false
bspc config gapless_monocle               false
bspc config focus_follows_pointer         true
bspc config center_pseudo_tiled			  true
bspc config pointer_modifier              mod4 
bspc config pointer_action1               move 
bspc config pointer_action2               resize_side 
bspc config pointer_action3               resize_corner
bspc config automatic_scheme              longest_side
bspc config initial_polarity              second_child
bspc config remove_disabled_monitors      true 
bspc config remove_unplugged_monitors 	  true
bspc config merge_overlapping_monitors    true
bspc config pointer_motion_interval       5
#bspc wm --adopt-orphans

#  ╔═╗╦ ╦╔╦╗╔═╗╔═╗╔╦╗╔═╗╦═╗╔╦╗
#  ╠═╣║ ║ ║ ║ ║╚═╗ ║ ╠═╣╠╦╝ ║
#  ╩ ╩╚═╝ ╩ ╚═╝╚═╝ ╩ ╩ ╩╩╚═ ╩

# Set system vars
"${rice_path}"/src/SetSysVars

# Launch sxhkd daemon
pidof -q sxhkd || { sxhkd -c $shxkd_cfgfile & }

# Load current theme
"${rice_path}"/src/ApplyThemeConfig

# Launch picom
pidof -q picom || { picom --config $picom_cfgfile & }

# Launch eww daemon
pidof -q eww || { eww -c $eww_widget_dir daemon & }

# Launch clipboard daemon
pidof -q greenclip || { greenclip daemon & }

# Launch polkit
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }

# Fix cursor
xsetroot -cursor_name left_ptr