#!/usr/bin/env bash
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝

########### Def vars ###########

# Retrieve the $rice_path variables
source "${HOME}"/.config/punk_records/Poneglyph

# Set environment variables
export PATH="$script_bin_path:$PATH"
export XDG_CURRENT_DESKTOP='bspwm'

## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

#  ╦ ╦╔═╗╦═╗╦╔═╔═╗╔═╗╔═╗╔═╗╔═╗╔═╗
#  ║║║║ ║╠╦╝╠╩╗╚═╗╠═╝╠═╣║  ║╣ ╚═╗
#  ╚╩╝╚═╝╩╚═╩ ╩╚═╝╩  ╩ ╩╚═╝╚═╝╚═╝

# Workspace layout:
#  1.  file   : File manager applications (Thunar, Ranger, Yazi, etc.)
#  2.  web    : Web browsers (Firefox, Google-Chrome, etc.)
#  3.  code   : Editors/IDEs (VSCode, Neovim, etc.)
#  4.  term   : Terminals (Alacritty, Kitty, etc.)
#  5.  chat   : Communication apps (Discord, Telegram, Slack, etc.)
#  6.  ref    : References, notes, and documents (PDF, Obsidian, etc.)
#  7.  extra  : Additional terminals (debugging, logs, or backups)
#  8.  chill  : Media players or entertainment (Spotify, MPV, etc.)
#  9.  tool   : Specialized tools (VirtualBox, Blender, OBS, etc.)
#  10. misc   : Miscellaneous usage (scripts, system stats, or testing)

# Get the name of the primary monitor
primary_monitor=$(xrandr | grep "connected primary" | awk '{print $1}')
# Get the list of connected monitors excluding the primary monitor
external_monitors=($(xrandr | awk '/ connected / && !/ primary/ {print $1}'))

case "${#external_monitors[@]}" in
	0)
        # Use primary monitor with default 8 workspaces
		bspc monitor "$primary_monitor" -d 'file' 'web' 'code' 'term' 'chat' 'chill' 'tool' 'misc'
		;;
	1)
        # Two monitors: Allocate workspaces evenly between primary and one external monitor
		bspc monitor "$primary_monitor" -d 'file' 'web' 'code' 'term' 'chat'
		bspc monitor "${external_monitors[0]}" -d 'ref' 'extra' 'chill' 'tool' 'misc'
		bspc wm -O "$primary_monitor" "${external_monitors[0]}"
		;;
	2)
        # Three monitors: Assign workspaces in a 4-3-3 distribution
		bspc monitor "${external_monitors[0]}" -d 'file' 'web' 'chat' 'ref'
		bspc monitor "$primary_monitor" -d 'code' 'term' 'tool'
		bspc monitor "${external_monitors[1]}" -d 'extra' 'chill' 'misc'
		bspc wm -O "${external_monitors[0]}" "$primary_monitor" "${external_monitors[1]}"
		;;
esac

#  ╔╗ ╔═╗╔═╗╦ ╦╔╦╗  ╔═╗╔═╗╔╗╔╔═╗╦╔═╗
#  ╠╩╗╚═╗╠═╝║║║║║║  ║  ║ ║║║║╠╣ ║║ ╦
#  ╚═╝╚═╝╩  ╚╩╝╩ ╩  ╚═╝╚═╝╝╚╝╚  ╩╚═╝

bspc config external_rules_command $external_rules_cfgfile

bspc config split_ratio                   0.5
bspc config single_monocle                true
bspc config borderless_monocle            false
bspc config gapless_monocle               false
bspc config focus_follows_pointer         true
bspc config center_pseudo_tiled			  true
bspc config pointer_modifier              mod4 
bspc config pointer_action1               move 
bspc config pointer_action2               resize_side 
bspc config pointer_action3               resize_corner
bspc config automatic_scheme              longest_side
bspc config initial_polarity              second_child
bspc config remove_disabled_monitors      true 
bspc config remove_unplugged_monitors 	  true
bspc config merge_overlapping_monitors    true
bspc config pointer_motion_interval       5
#bspc wm --adopt-orphans

#  ╔═╗╦ ╦╔╦╗╔═╗╔═╗╔╦╗╔═╗╦═╗╔╦╗
#  ╠═╣║ ║ ║ ║ ║╚═╗ ║ ╠═╣╠╦╝ ║
#  ╩ ╩╚═╝ ╩ ╚═╝╚═╝ ╩ ╩ ╩╩╚═ ╩

# Launch sxhkd daemon
pidof -q sxhkd || { sxhkd -c $shxkd_cfgfile & }

# Load current theme
"${script_bin_path}"/ApplyThemeConfig

# Launch picom
pidof -q picom || { picom --config $picom_cfgfile & }

# Launch eww daemon
pidof -q eww || { eww -c $eww_widget_dir daemon & }

# Launch clipboard daemon
pidof -q greenclip || { greenclip daemon & }

# Launch polkit
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }

# Fix cursor
xsetroot -cursor_name left_ptr