#!/bin/bash

# See man zscroll for documentation of the following parameters
# https://github.com/noctuid/zscroll
zscroll_cmd() {
    zscroll -l 30 \
        --delay 0.1 \
        --scroll-padding "           " \
        --match-command "MusicControl --status-in-polybar" \
        --match-text "Playing" "--scroll 1" \
        --match-text "Paused" "--scroll 0" \
        --update-check true "MusicControl --status-in-polybar" &

    wait
}

# Check if zscroll is installed
if ! command -v zscroll &> /dev/null; then
    MusicControl --status-in-polybar
else
    zscroll_cmd
fi