#!/usr/bin/env bash

source "${HOME}"/.config/punk_records/Poneglyph

# Create system.ini
if [[ ! -f "$sys_vars_file" ]]; then
	touch "$sys_vars_file"
	chmod a+rwx "$sys_vars_file"
fi

cat > $sys_vars_file << EOF
;  ╔═╗╦ ╦╔═╗╔╦╗╔═╗╔╦╗  ╦  ╦╔═╗╦═╗╦╔═╗╔╗ ╦  ╔═╗╔═╗
;  ╚═╗╚╦╝╚═╗ ║ ║╣ ║║║  ╚╗╔╝╠═╣╠╦╝║╠═╣╠╩╗║  ║╣ ╚═╗
;  ╚═╝ ╩ ╚═╝ ╩ ╚═╝╩ ╩   ╚╝ ╩ ╩╩╚═╩╩ ╩╚═╝╩═╝╚═╝╚═╝
; The variables for the polybar modules are taken from this file.

;; Edit according to your system
;; Run "ls -1 /sys/class/power_supply/" to list available batteries and power adapters.
;; Run "ls -1 /sys/class/backlight/" to list available graphics cards.
;; Run "ip -o link show up | awk -F': ' '{print $2}' | grep -vE '^(lo|docker|veth|br-)'" to get active network interface.
;; Run "xrandr | awk '/ connected /'" to get list of connected monitors.

[system]
adapter = 
battery = 
graphics_card = 
network_interface =  
network_interface_2 = 
primary_monitor = 
EOF


function setup_system_vars() {
	########## Get values ##########
	ADAPTER=$(find /sys/class/power_supply -maxdepth 1 -type l -name "A[CD]*" | head -n1 | xargs basename)
	BATTERY=$(find /sys/class/power_supply -maxdepth 1 -type l -name "BAT*" | head -n1 | xargs basename)

	CARD=$(find /sys/class/backlight -maxdepth 1 -type l | head -n1 | xargs basename)

	readarray -t ALL_NET < <(ip -o link show up | awk -F': ' '{print $2}' | grep -vE '^(lo|docker|veth|br-)')
	PRIMARY_NET=$(ip -o route get 1 | awk '{print $5; exit}')
	SECONDARY_NET=$(printf '%s\n' "${ALL_NET[@]}" | grep -v "$PRIMARY_NET" | head -n1)

	PRIMARY_MONITOR=$(xrandr | grep "connected primary" | awk '{print $1}')
	EXTERNAL_MONITORS=($(xrandr | awk '/ connected / && !/ primary/ {print $1}'))
	
	########## Set values ##########
	[[ -n "$ADAPTER" ]] && sed -i "s/adapter = .*/adapter = $ADAPTER/" "$sys_vars_file"
	[[ -n "$BATTERY" ]] && sed -i "s/battery = .*/battery = $BATTERY/" "$sys_vars_file"

	[[ -n "$CARD" ]] && sed -i "s/graphics_card = .*/graphics_card = $CARD/" "$sys_vars_file"

	[[ -n "$PRIMARY_NET" ]] && sed -i "s/network_interface = .*/network_interface = $PRIMARY_NET/" "$sys_vars_file"
	[[ -n "$SECONDARY_NET" ]] && sed -i "s/network_interface_2 = .*/network_interface_2 = $SECONDARY_NET/" "$sys_vars_file"

	[[ -n "$PRIMARY_MONITOR" ]] && sed -i "s/primary_monitor = .*/primary_monitor = $PRIMARY_MONITOR/" "$sys_vars_file"
	if [[ ${#EXTERNAL_MONITORS[@]} -gt 0 ]]; then
		for i in "${!EXTERNAL_MONITORS[@]}"; do
			echo "external_monitor_$((i + 1)) = ${EXTERNAL_MONITORS[i]}" >> "$sys_vars_file"
		done
	fi
}

# Run setup
setup_system_vars