#!/usr/bin/env bash

##### ---------- Theme dir ---------- ######
rice_folder="punk_records"
rice_path="$HOME/.config/$rice_folder"

##### ---------- System info ---------- ######
sysVars="$HOME/.config/bspwm/SystemVars/system.ini"

##### ---------- Current Rice ---------- ######
read -r RICE < "$rice_path"/.rice

##### ---------- Polybar theme path ---------- ######
poly_dir="$HOME/.config/polybar/${RICE}"

##### ---------- Toggle the source audio player ---------- ######
current_player="spotify"

toggle_player() {
    # Find the current position of the current_control value in the `players` array
    # and calculate the index of the next value
    local players=("$@")
    for i in "${!players[@]}"; do
        if [ "${players[$i]}" = "$current_player" ]; then
            index=$i
            break
        fi
    done
    next_index=$(( (index + 1) % ${#players[@]} ))
    next_value="${players[$next_index]}"

    # Update the value of current_control in the file
    sed -i "s/current_player=\"$current_player\"/current_player=\"$next_value\"/" "$HOME"/.config/bspwm/SystemVars/EnvVars
}

# Call the function with the desired options, example:
# toggle_player "MPD" "Spotify" "playerctld"