[general]
import = ["~/.config/alacritty/rice-colors.toml"]
live_config_reload = true

[font]
size = 10
builtin_box_drawing = true

[font.normal]
family = "JetBrainsMono Nerd Font"

[cursor]
blink_interval = 550
unfocused_hollow = false
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Block"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_title = true
dynamic_padding = true

[window.padding]
x = 15
y = 15

[scrolling]
history = 10000
multiplier = 3

[bell]
animation = "Linear"
duration = 0
command = { program = "paplay", args = ["/usr/share/sounds/freedesktop/stereo/dialog-error.oga"] }