# Default colors
[colors.primary]
background = "#EAEAEA"
foreground = "#1A1A1A"

# Cursor colors
[colors.cursor]
cursor = "#2e2e2e"
text = "#FFFFFF"

# Normal colors
[colors.normal]
black = "#202020"
red = "#f22929"
green = "#088538"
yellow = "#deae00"
blue =  "#336DFF"
magenta = "#9B59B6"
cyan = "#038b8c"
white = "#FDFDFD"

# Bright colors
[colors.bright]
black = "#2e2e2e"
red = "#ed0707"
green = "#149445"
yellow = "#ffcf21"
blue = "#5D9EFF"
magenta = "#bd6eeb"
cyan = "#00A7AA"
white = "#FFFFFF"
