# Default colors
[colors.primary]
background = "#14151c"
foreground = "#FDFDFD"

# Cursor colors
[colors.cursor]
cursor = "#FDFDFD"
text = "#14151c"

# Normal colors
[colors.normal]
black = "#262831"
red = "#F37F97"
green = "#60c98c"
yellow = "#F2A272"
blue =  "#8897F4"
magenta = "#B043D1"
cyan = "#79E6F3"
white = "#a9b1d6"

# Bright colors
[colors.bright]
black = "#414868"
red = "#f7768e"
green = "#60c98c"
yellow = "#F2A272"
blue = "#8897F4"
magenta = "#B043D1"
cyan = "#79E6F3"
white = "#c0caf5"
